import 'package:flutter/material.dart';

import '../models/platform_capability.dart';
import '../models/tool_experience.dart';

class ToolDefinition {
  const ToolDefinition({
    required this.id,
    required this.name,
    required this.description,
    required this.category,
    required this.icon,
  });

  final String id;
  final String name;
  final String description;
  final String category;
  final IconData icon;

  ToolExperienceProfile get experience => toolExperienceFor(id);

  List<CapabilityId> get capabilities => switch (id) {
    'wifi' || 'wifi_roaming' => const [CapabilityId.wifiScan],
    'bluetooth_debug' => const [
      CapabilityId.bluetoothLowEnergy,
      CapabilityId.bluetoothClassic,
    ],
    'smb' => const [CapabilityId.smb],
    'traffic_monitor' => const [
      CapabilityId.interfaceTraffic,
      CapabilityId.processTraffic,
    ],
    'packet_capture' => const [CapabilityId.packetCapture],
    _ => const [],
  };

  Color get color => switch (category) {
    'Wi‑Fi' => const Color(0xFF2E86F6),
    '网络诊断' => const Color(0xFF18A5A0),
    '流量与性能' => const Color(0xFFF09A45),
    '远程与服务' => const Color(0xFF7069E8),
    'IP 与寻址' => const Color(0xFF3AA875),
    'API 与协议' => const Color(0xFFE16A92),
    '数据与转换' => const Color(0xFF3B82C4),
    '安全与标识' => const Color(0xFFC06391),
    '后端工程' => const Color(0xFF4E7D70),
    _ => const Color(0xFF3578F6),
  };
}

const toolCatalog = [
  ToolDefinition(
    id: 'doctor',
    name: '一键网络医生',
    description: '定位无线、网关、DNS 与互联网问题',
    category: '网络诊断',
    icon: Icons.health_and_safety_outlined,
  ),
  ToolDefinition(
    id: 'network',
    name: '网络出口',
    description: '公网出口、接口、网关与 DNS',
    category: 'Wi‑Fi',
    icon: Icons.route_outlined,
  ),
  ToolDefinition(
    id: 'network_events',
    name: '网络事件监视',
    description: '路由、VPN、DNS、网关和地址变化',
    category: '网络诊断',
    icon: Icons.timeline_rounded,
  ),
  ToolDefinition(
    id: 'wifi',
    name: 'Wi‑Fi 分析',
    description: '连接信息、附近 AP 与信道',
    category: 'Wi‑Fi',
    icon: Icons.wifi_find,
  ),
  ToolDefinition(
    id: 'wifi_roaming',
    name: 'Wi-Fi 漫游分析',
    description: 'BSSID 切换、RSSI、丢包与断流窗口',
    category: 'Wi‑Fi',
    icon: Icons.cell_tower_rounded,
  ),
  ToolDefinition(
    id: 'ping',
    name: 'Ping',
    description: 'ICMP、TCP、UDP Echo / Probe',
    category: '网络诊断',
    icon: Icons.network_ping,
  ),
  ToolDefinition(
    id: 'traceroute',
    name: '路由追踪',
    description: '逐跳延迟、地址和地理位置',
    category: '网络诊断',
    icon: Icons.alt_route,
  ),
  ToolDefinition(
    id: 'dns',
    name: 'DNS 查询',
    description: '完整记录、指定 DNS、DoT 与 DoH',
    category: '网络诊断',
    icon: Icons.dns_outlined,
  ),
  ToolDefinition(
    id: 'ntp',
    name: 'NTP 时间查询',
    description: '偏移、抖动、根距离与时间源质量',
    category: '网络诊断',
    icon: Icons.more_time_rounded,
  ),
  ToolDefinition(
    id: 'ports',
    name: '端口检测',
    description: '单端口、列表与范围扫描',
    category: '网络诊断',
    icon: Icons.radar,
  ),
  ToolDefinition(
    id: 'lan',
    name: '局域网扫描',
    description: '发现、筛选和联动诊断在线主机',
    category: '网络诊断',
    icon: Icons.lan_outlined,
  ),
  ToolDefinition(
    id: 'discovery',
    name: '服务发现',
    description: 'SSDP / UPnP 与 mDNS / Bonjour',
    category: '网络诊断',
    icon: Icons.podcasts,
  ),
  ToolDefinition(
    id: 'wol',
    name: 'Wake-on-LAN',
    description: '向局域网设备发送魔术包',
    category: '网络诊断',
    icon: Icons.power_settings_new,
  ),
  ToolDefinition(
    id: 'http',
    name: 'HTTP 诊断',
    description: '状态、响应头、耗时与正文',
    category: 'API 与协议',
    icon: Icons.http,
  ),
  ToolDefinition(
    id: 'api_workbench',
    name: 'API 调试台',
    description: 'REST、WebSocket、SSE 与 MQTT',
    category: 'API 与协议',
    icon: Icons.api,
  ),
  ToolDefinition(
    id: 'path_mtu',
    name: '路径 MTU',
    description: '禁止分片探测与链路 MTU 上限',
    category: '网络诊断',
    icon: Icons.straighten,
  ),
  ToolDefinition(
    id: 'traffic_monitor',
    name: '实时流量监视',
    description: '上下行速率、活跃连接与协议分布',
    category: '流量与性能',
    icon: Icons.monitor_heart_outlined,
  ),
  ToolDefinition(
    id: 'packet_capture',
    name: '离线抓包分析',
    description: '协议层级、I/O、端点与双向会话',
    category: '流量与性能',
    icon: Icons.file_open_outlined,
  ),
  ToolDefinition(
    id: 'stun',
    name: 'STUN 映射',
    description: '查看 UDP 映射地址与端口',
    category: '网络诊断',
    icon: Icons.compare_arrows,
  ),
  ToolDefinition(
    id: 'tls',
    name: 'TLS 证书检查',
    description: '握手、信任链、有效期与指纹',
    category: 'API 与协议',
    icon: Icons.verified_user_outlined,
  ),
  ToolDefinition(
    id: 'ownership',
    name: 'RDAP / ASN',
    description: 'IP 注册信息与 BGP 路由归属',
    category: 'IP 与寻址',
    icon: Icons.account_tree_outlined,
  ),
  ToolDefinition(
    id: 'telnet',
    name: 'Telnet 终端',
    description: '交互会话与基础协议协商',
    category: '远程与服务',
    icon: Icons.cable,
  ),
  ToolDefinition(
    id: 'socket_debug',
    name: 'TCP / UDP 调试助手',
    description: '客户端、服务端、Hex 与收发日志',
    category: '远程与服务',
    icon: Icons.swap_calls,
  ),
  ToolDefinition(
    id: 'local_server',
    name: '本地测试服务',
    description: '在本机启动 HTTP / TCP Echo 服务',
    category: '远程与服务',
    icon: Icons.dns_outlined,
  ),
  ToolDefinition(
    id: 'syslog',
    name: 'Syslog 接收器',
    description: 'UDP / TCP 实时接收设备日志',
    category: '远程与服务',
    icon: Icons.receipt_long_outlined,
  ),
  ToolDefinition(
    id: 'snmp',
    name: 'SNMP 浏览器',
    description: 'v2c/v3 OID 查询、设备概览与 Walk',
    category: '远程与服务',
    icon: Icons.device_hub_outlined,
  ),
  ToolDefinition(
    id: 'bluetooth_debug',
    name: '蓝牙调试助手',
    description: 'BLE GATT 与经典蓝牙 Client / Server',
    category: '远程与服务',
    icon: Icons.bluetooth_searching,
  ),
  ToolDefinition(
    id: 'iperf',
    name: 'iPerf3',
    description: 'Client / Server、TCP / UDP',
    category: '流量与性能',
    icon: Icons.speed,
  ),
  ToolDefinition(
    id: 'smb',
    name: 'SMB 文件共享',
    description: 'SMB2/SMB3 浏览与文件传输',
    category: '远程与服务',
    icon: Icons.folder_shared,
  ),
  ToolDefinition(
    id: 'subnet',
    name: '子网计算',
    description: 'IPv4 / IPv6 边界与主机数量',
    category: 'IP 与寻址',
    icon: Icons.calculate_outlined,
  ),
  ToolDefinition(
    id: 'wildcard',
    name: '通配符掩码',
    description: '掩码、Wildcard 与 CIDR 互转',
    category: 'IP 与寻址',
    icon: Icons.pattern,
  ),
  ToolDefinition(
    id: 'ip_tools',
    name: 'IP 与 IPv6 转换',
    description: '分类、五类互转与格式化',
    category: 'IP 与寻址',
    icon: Icons.swap_horiz,
  ),
  ToolDefinition(
    id: 'geoip',
    name: 'IP 地理位置',
    description: '单条或最多 5 并发批量查询',
    category: 'IP 与寻址',
    icon: Icons.public,
  ),
  ToolDefinition(
    id: 'oui',
    name: 'MAC 厂商查询',
    description: 'MAC 查厂商、厂商反查注册前缀',
    category: 'IP 与寻址',
    icon: Icons.memory,
  ),
  ToolDefinition(
    id: 'mac_format',
    name: 'MAC 格式化',
    description: 'Linux、Windows、Cisco 格式互转',
    category: 'IP 与寻址',
    icon: Icons.transform,
  ),
  ToolDefinition(
    id: 'common_ports',
    name: '常用端口',
    description: '服务、协议与用途速查',
    category: 'IP 与寻址',
    icon: Icons.list_alt,
  ),
  ToolDefinition(
    id: 'base64',
    name: 'Base64',
    description: '标准与 URL-safe 编解码',
    category: '数据与转换',
    icon: Icons.data_object,
  ),
  ToolDefinition(
    id: 'qr',
    name: '二维码生成器',
    description: 'URL、Wi‑Fi、邮件、电话与短信',
    category: '数据与转换',
    icon: Icons.qr_code_2,
  ),
  ToolDefinition(
    id: 'url_codec',
    name: 'URL 编解码',
    description: '组件或完整 URL 转换',
    category: 'API 与协议',
    icon: Icons.link,
  ),
  ToolDefinition(
    id: 'timestamp',
    name: '时间戳转换',
    description: '时区、批量、计算与多语言代码',
    category: '数据与转换',
    icon: Icons.schedule,
  ),
  ToolDefinition(
    id: 'regex',
    name: '正则测试',
    description: '预设、捕获组、替换与兼容性诊断',
    category: '数据与转换',
    icon: Icons.rule,
  ),
  ToolDefinition(
    id: 'radix',
    name: '进制转换',
    description: '2～36 进制任意转换',
    category: '数据与转换',
    icon: Icons.numbers,
  ),
  ToolDefinition(
    id: 'bits',
    name: '位计算器',
    description: '8/16/32/64 位运算',
    category: '数据与转换',
    icon: Icons.calculate,
  ),
  ToolDefinition(
    id: 'diff',
    name: '文本对比',
    description: '按行或单词比较差异',
    category: '数据与转换',
    icon: Icons.difference_outlined,
  ),
  ToolDefinition(
    id: 'formatter',
    name: '代码格式化',
    description: 'JSON、XML、YAML、SQL',
    category: '数据与转换',
    icon: Icons.code,
  ),
  ToolDefinition(
    id: 'hash',
    name: 'Hash / HMAC',
    description: 'MD5、SHA-1/256/512 与 HMAC',
    category: '安全与标识',
    icon: Icons.fingerprint,
  ),
  ToolDefinition(
    id: 'jwt',
    name: 'JWT 解码器',
    description: 'Header、Payload 与时间声明',
    category: '安全与标识',
    icon: Icons.badge_outlined,
  ),
  ToolDefinition(
    id: 'generator',
    name: '标识与密码生成',
    description: 'UUID v4、ULID 与安全密码',
    category: '安全与标识',
    icon: Icons.auto_awesome,
  ),
  ToolDefinition(
    id: 'chmod',
    name: 'chmod 权限计算',
    description: '八进制与 rwx 权限互转',
    category: '安全与标识',
    icon: Icons.admin_panel_settings_outlined,
  ),
  ToolDefinition(
    id: 'unicode',
    name: 'Unicode 转换',
    description: '文本与 Unicode 转义互转',
    category: '数据与转换',
    icon: Icons.translate,
  ),
  ToolDefinition(
    id: 'html_entity',
    name: 'HTML 实体',
    description: 'HTML 特殊字符编码与还原',
    category: '数据与转换',
    icon: Icons.html,
  ),
  ToolDefinition(
    id: 'hexdump',
    name: 'Hexdump',
    description: '字节偏移、十六进制与 ASCII',
    category: '数据与转换',
    icon: Icons.view_module_outlined,
  ),
  ToolDefinition(
    id: 'url_parser',
    name: 'URL 解析器',
    description: 'Host、路径、Query 与 Fragment',
    category: 'API 与协议',
    icon: Icons.account_tree_outlined,
  ),
  ToolDefinition(
    id: 'compression',
    name: 'Gzip 压缩',
    description: 'Gzip 与 Base64 离线压缩解压',
    category: '数据与转换',
    icon: Icons.compress,
  ),
  ToolDefinition(
    id: 'data_convert',
    name: '结构化数据转换',
    description: 'JSON、YAML 与 CSV 双向转换',
    category: '数据与转换',
    icon: Icons.transform_outlined,
  ),
  ToolDefinition(
    id: 'json_query',
    name: 'JSONPath 查询',
    description: '属性、数组下标与通配查询',
    category: '数据与转换',
    icon: Icons.manage_search,
  ),
  ToolDefinition(
    id: 'cron',
    name: 'Cron 表达式',
    description: '语义说明与未来执行时间',
    category: '后端工程',
    icon: Icons.update,
  ),
  ToolDefinition(
    id: 'endian',
    name: '字节序与整数',
    description: '大小端、十六进制和整数查看',
    category: '数据与转换',
    icon: Icons.swap_vert,
  ),
  ToolDefinition(
    id: 'user_agent',
    name: 'User-Agent 解析',
    description: '浏览器、系统、设备与爬虫识别',
    category: 'API 与协议',
    icon: Icons.devices_other,
  ),
  ToolDefinition(
    id: 'json_workbench',
    name: 'JSON 与数据工作台',
    description: '格式化、JSONPath、Schema、Diff 与模型生成',
    category: '数据与转换',
    icon: Icons.account_tree_rounded,
  ),
  ToolDefinition(
    id: 'sql_toolkit',
    name: 'SQL 工具箱',
    description: '格式化、IN List 与 JSON 生成 INSERT',
    category: '后端工程',
    icon: Icons.storage_rounded,
  ),
  ToolDefinition(
    id: 'id_inspector',
    name: 'ID 与分布式标识',
    description: 'UUID、ULID、ObjectId 与 Snowflake 解析',
    category: '安全与标识',
    icon: Icons.manage_accounts_outlined,
  ),
  ToolDefinition(
    id: 'semver',
    name: 'Semantic Version',
    description: '版本合法性、预发布与优先级比较',
    category: '后端工程',
    icon: Icons.new_releases_outlined,
  ),
  ToolDefinition(
    id: 'http_metadata',
    name: 'HTTP 元数据分析',
    description: '缓存、Cookie、CORS 与安全响应头诊断',
    category: 'API 与协议',
    icon: Icons.rule_folder_outlined,
  ),
  ToolDefinition(
    id: 'log_inspector',
    name: '日志分析器',
    description: 'JSON Lines、级别、Trace ID 与 ANSI 清理',
    category: '后端工程',
    icon: Icons.find_in_page_outlined,
  ),
];
